version: '3.5'
services:
  web:
    build:
      context: .
    image: sean-node
    container_name: sean-node
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro